//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg5_semana2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO
    {
        public int CARNE { get; set; }
        public string NOMBRE { get; set; }
        public int EDAD { get; set; }
        public string GENERO { get; set; }
    }
}
